### ISSUE TITLE
Update: Misleading console error displayed in inspector tool within all courses

### ISSUE THREAD

**Issue by eleanor-heath** [adaptlearning/adapt-contrib-core#349] opened 2023-04-12 11:18 UTC
### Subject of the issue/enhancement/features
The below console error is shown in the inspector tools on all course outputs:
<img width="563" alt="Screenshot 2023-04-12 at 12 09 08" src="https://user-images.githubusercontent.com/61159216/231440028-bf7cb948-74df-4e16-a545-c8b5965b872f.png">

These are the arguments that are passed through to the set function
<img width="397" alt="Screenshot 2023-04-12 at 12 09 33" src="https://user-images.githubusercontent.com/61159216/231440172-0a26bdc7-a3f3-415a-bae0-4b98edaa1034.png">

<img width="844" alt="Screenshot 2023-04-12 at 11 49 40" src="https://user-images.githubusercontent.com/61159216/231440236-096a78c6-7527-4a29-8a42-33d275aac21d.png">

The second object where the pluginName should be set does not exist, I am assuming this is due to the properties that are being set are being derived from the main adapt.js.
<img width="844" alt="Screenshot 2023-04-12 at 11 49 40" src="https://user-images.githubusercontent.com/61159216/231441083-6cf884cb-5609-4f69-b2ef-177a8ef487da.png">

### Steps to reproduce
Create a course with a multiple choice question. Add a few answers to the multiple choice question, save, then preview and inspect the page. The console error will be presented.

### Expected behaviour
I should not see a console error for something that will not impact my course.

### Actual behaviour
I am seeing a console error "Must supply a pluginName to change a locked attribute" in the inspector tool on all courses I create.

**Comment by oliverfoster** [comment] 2023-04-12 11:54
Duplicate of: https://github.com/adaptlearning/adapt-contrib-core/issues/319

Pr to fix: https://github.com/adaptlearning/adapt-contrib-core/pull/347

**Comment by oliverfoster** [comment] 2023-04-13 17:30
Closed as duplicate of #319

**Closed by oliverfoster** 2023-04-13 17:30 UTC
Labels: bug
