### ISSUE TITLE
inview not triggering

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt-contrib-core#590] opened 2024-10-11 18:51 UTC
### Subject of the issue
I was alerted to an issue where a text component at the top of a page would not complete. The user lands on the page and the text component is fully visible. It should therefore be complete.

It's possible to replicate this in the **latest framework**. In my test I looked at c-100 and I had disabled the animation on the parent block.

I have tested in Firefox and Edge and observed the problem in both browsers.

Note also that if I scroll down from the top of the page sometimes c-100 will complete, but sometimes (scrolling slowly with the mouse wheel) it will not complete (see attached animation)

I have tried patching with the fix suggested for #588 but this did not resolve the issue.

![Animation](https://github.com/user-attachments/assets/b2d10f09-b3c3-4f79-a8de-f259ca8f417c)

**Comment by oliverfoster** [comment] 2024-10-11 21:35
Duplicate of https://github.com/adaptlearning/adapt-contrib-core/issues/588

**Closed** 2024-10-11 21:36 UTC
