### ISSUE TITLE
Multiple render calls on page load

### ISSUE THREAD

**Issue by cahirodoherty-learningpool** [adaptlearning/adapt-contrib-core#261] opened 2022-11-04 16:13 UTC
### Subject of the issue/enhancement/features
Component render calls are being called multiple times on page load.
This must surely be unintended behaviour and a drain - an investigation is needed

### Your environment
* v5.22.5
* Chrome
* MacOS

### Steps to reproduce
Create a vanilla course with a text component
Preview the course and breakpoint on the text.jsx return

### Expected behaviour
This render would only be invoked once on page load

### Actual behaviour
Hitting the breakpoint more than 10 times!

**Comment by oliverfoster** [comment] 2022-11-07 09:36
Duplicate of #258

**Closed** 2022-11-22 15:12 UTC
Labels: bug
