### ISSUE TITLE
`calculateLevel` issue when resetting a branched assessment

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-core#355] opened 2023-04-24 15:08 UTC
When resetting a branched assessment, the following line errors when attempting to find a branched model id in the data:
https://github.com/adaptlearning/adapt-contrib-core/blob/master/js/a11y.js#L219
```JavaScript
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'get')
    at calculateLevel (a11y.js:222:46)
    at calculateLevel (a11y.js:229:14)
    at calculateLevel (a11y.js:229:14)
    at A11y.ariaLevel (a11y.js:231:12)
    at Object.a11y_aria_level (helpers.js:345:32)
    at Object.c (handlebars.min.js:27:19853)
    at Object.main (templates.js:389:120)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at Object.<anonymous> (templates.js:26:17)
```

**Comment by oliverfoster** [comment] 2023-11-07 09:17
There is not enough information here to reproduce the issue. Could you find out which component is rendering its template and when it is doing it please?

**Comment by oliverfoster** [comment] 2023-11-07 09:18
Duplicate of https://github.com/adaptlearning/adapt-contrib-core/issues/453

**Closed by oliverfoster** 2023-11-07 09:18 UTC
Labels: bug

**Comment by danielghost** [comment] 2024-04-10 16:43
Was still an issue, but resolved by https://github.com/adaptlearning/adapt-contrib-core/pull/517.
