### ISSUE TITLE
inview calculations can stop playback for fullscreen videos

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-core#64] opened 2022-02-17 11:52 UTC
If a media component is located far from the top of the page (can only be replicated on long scrolling pages), when entering fullscreen mode via the player controls, the playback is stopped because the `component__widget` is off screen. This can be rectified by changing the inview element to be the actual video container, but then it falls into the out of bounds condition.

**Comment by oliverfoster** [comment] 2022-02-21 11:57
duplicate of https://github.com/adaptlearning/adapt-contrib-media/issues/226

**Closed by oliverfoster** 2022-02-21 11:57 UTC
Labels: bug
